apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.5
          args:
            - "start-dev"
            - "--import-realm"
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin_password"
            - name: KC_HOSTNAME
              value: "localhost"
            - name: KC_HOSTNAME_PORT
              value: "8888"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
          volumeMounts:
            - name: keycloak-init
              mountPath: /opt/keycloak/data/import
              readOnly: true
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-init
          configMap:
            name: keycloak-init-realm
        - name: keycloak-data
          emptyDir: {} 