apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  kafka.properties: |
    # KRaft Configuration
    node.id=1
    process.roles=broker,controller
    controller.quorum.voters=1@kafka:9093
    
    # Listeners
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka:9092
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    
    # Storage
    log.dirs=/tmp/kraft-combined-logs
    
    # Replication
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    
    # Performance
    group.initial.rebalance.delay.ms=0
    auto.create.topics.enable=true
    delete.topic.enable=true
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    
    # Additional KRaft settings
    controller.quorum.election.timeout.ms=1000
    controller.quorum.fetch.timeout.ms=2000 