apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  type: ClusterIP
  ports:
    - port: 4566
      targetPort: 4566
      protocol: TCP
      name: localstack-api
  selector:
    app: localstack 