apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "adminpassword123"
            - name: MONGO_INITDB_DATABASE
              value: "raffles_db"
          args:
            - "--auth"
          volumeMounts:
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-init
          configMap:
            name: mongo-init-scripts
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
