apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgres
  labels:
    app: sonarqube-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: sonarqube-postgres 